/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.xh.vdcluster.rpc;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum SeviceStatusType implements TEnum {
  SERVICE_NO_SUCH_ID(0),
  SERVICE_NORMAL(1),
  SERVICE_STREAM_CONNECTING(2),
  SERVICE_STREAM_FAULT(3),
  SERVICE_FILE_FAULT(4),
  SERVICE_STREAM_DECODE_FAULT(5),
  SERVICE_DELETE_SUCCESS(6),
  SERVICE_START_SUCCESS(7),
  SERVICE_START_FALIED(8),
  SERVICE_DELETE_SUCESS(9),
  SERVICE_DELETE_FALIED(10);

  private final int value;

  private SeviceStatusType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static SeviceStatusType findByValue(int value) { 
    switch (value) {
      case 0:
        return SERVICE_NO_SUCH_ID;
      case 1:
        return SERVICE_NORMAL;
      case 2:
        return SERVICE_STREAM_CONNECTING;
      case 3:
        return SERVICE_STREAM_FAULT;
      case 4:
        return SERVICE_FILE_FAULT;
      case 5:
        return SERVICE_STREAM_DECODE_FAULT;
      case 6:
        return SERVICE_DELETE_SUCCESS;
      case 7:
        return SERVICE_START_SUCCESS;
      case 8:
        return SERVICE_START_FALIED;
      case 9:
        return SERVICE_DELETE_SUCESS;
      case 10:
        return SERVICE_DELETE_FALIED;
      default:
        return null;
    }
  }
}
